### ISSUE TITLE
bluepy.btle.BTLEDisconnectError: Device disconnected

### ISSUE THREAD

**Issue by matbrewer396** [zewelor/bt-mqtt-gateway#102]
Hi

Trying to get this running on a Pi Zero W i keep getting this error Device disconnected.

I can see the device when I run  hcitool lescan however the first time i used it i got a "Set scan parameters failed: Input/output error" error and had to run the below to get it working

`sudo hciconfig hci0 down
sudo hciconfig hci0 up`

log from   sudo ./gateway.py -d, i sent "ON" to "bt-mqtt-gateway/switchbot/kitchen/light/set"
`
2019-09-14 10:22:46,873 INFO bt-mqtt-gw gateway.py:61:<module> - Starting
2019-09-14 10:22:46,880 DEBUG bt-mqtt-gw.mqtt mqtt.py:30:__init__ - Setting LWT to: bt-mqtt-gateway/lwt_topic
2019-09-14 10:22:47,351 INFO bt-mqtt-gw.workers.switchbot switchbot.py:19:_setup - Adding 1 switchbot devices
2019-09-14 10:22:47,354 INFO bt-mqtt-gw.workers.switchbot switchbot.py:21:_setup - Adding switchbot device 'light' (D3:A7:92:AA:6D:B3)
2019-09-14 10:22:47,357 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:103:register_workers - Added switchbot worker with 60 seconds interval and a 35 seconds timeout
2019-09-14 10:22:51,670 DEBUG bt-mqtt-gw.mqtt mqtt.py:116:callbacks_subscription - Subscribing to: bt-mqtt-gateway/switchbot/kitchen/update_interval
2019-09-14 10:22:51,679 DEBUG bt-mqtt-gw.mqtt mqtt.py:116:callbacks_subscription - Subscribing to: bt-mqtt-gateway/switchbot/+/+/set
2019-09-14 10:22:51,687 DEBUG bt-mqtt-gw.mqtt mqtt.py:116:callbacks_subscription - Subscribing to: bt-mqtt-gateway/homeassistant/status
2019-09-14 10:22:51,717 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:171:update_all - Updating all workers
2019-09-14 10:22:52,103 DEBUG bt-mqtt-gw.workers.switchbot switchbot.py:31:status_update - Updating 1 switchbot devices
2019-09-14 10:22:52,106 DEBUG bt-mqtt-gw.workers.switchbot switchbot.py:33:status_update - Updating switchbot device 'light' (D3:A7:92:AA:6D:B3)
2019-09-14 10:22:52,109 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:64:execute - Execution result of command SwitchbotWorker.status_update: [{'payload': 'OFF', 'topic': 'switchbot/kitchen/light'}]
2019-09-14 10:23:24,535 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:203:_on_command_wrapper - Received command for switchbot on bt-mqtt-gateway/switchbot/kitchen/light/set: b'ON'
2019-09-14 10:23:24,544 DEBUG bt-mqtt-gw.workers.switchbot switchbot.py:66:on_command - Setting ON on switchbot device 'light' (D3:A7:92:AA:6D:B3)
2019-09-14 10:23:25,464 ERROR bt-mqtt-gw.workers.switchbot logger.py:50:log_exception - Error setting ON on switchbot device 'light' (D3:A7:92:AA:6D:B3): BTLEDisconnectError
Traceback (most recent call last):
  File "/home/pi/bt-mqtt-gateway/workers/switchbot.py", line 74, in on_command
    "cba20002-224d-11e6-9fb8-0002a5d5c51b"
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 144, in getCharacteristics
    self.chars = [] if self.hndEnd <= self.hndStart else self.peripheral.getCharacteristics(self.hndStart, self.hndEnd)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 508, in getCharacteristics
    rsp = self._getResp('find')
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 407, in _getResp
    resp = self._waitResp(wantType + ['ntfy', 'ind'], timeout)
  File "/usr/local/lib/python3.5/dist-packages/bluepy/btle.py", line 362, in _waitResp
    raise BTLEDisconnectError("Device disconnected", resp)
bluepy.btle.BTLEDisconnectError: Device disconnected
2019-09-14 10:23:25,510 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:64:execute - Execution result of command SwitchbotWorker.on_command: []`

Config.yaml: 
```
mqtt:
  host: 192.168.1.253
  port: 1883
  username: mqtt
  password: MyPassword
  #ca_cert: /etc/ssl/certs/ca-certificates.crt # Uncomment to enable MQTT TLS, update path to appropriate location.
  #ca_verify: False              # Verify TLS certificate chain and host, disable for testing with self-signed certificates, default to True
  topic_prefix: bt-mqtt-gateway         # All messages will have that prefix added, remove if you dont need this.
  client_id: bt-mqtt-gateway
  availability_topic: lwt_topic

manager:
  sensor_config:
    topic: homeassistant
    retain: true
  topic_subscription:
    update_all:
      topic: homeassistant/status
      payload: online
  command_timeout: 35           # Timeout for worker operations. Can be removed if the default of 35 seconds is sufficient.
  workers:
    switchbot:
      args:
        devices:
          light: D3:A7:92:AA:6D:B3
        topic_prefix: switchbot/kitchen
        state_topic_prefix: switchbot/kitchen
      topic_subscription: switchbot/+/+/set
      update_interval: 60
```

Anyone got anyway idea why isnt this isnt working?

Regards 

Matt
