### ISSUE TITLE
Does this work with Tiles Ble trackers? 

### ISSUE THREAD

**Issue by MattL0** [zewelor/bt-mqtt-gateway#178]
**Device name / url**

Any tiles 

**another platform**
Jeedom plugin BLEA 

**Functions and features**
Just want to know if the tile is present or not . Time configurable

**Checklist**
- X I understand that supporting a device, that no one owns or uses, may required a long wait time, or might never end up being supported.

**Comment by diplix** [comment]
works for me, i use it with some tile pro trackers and it works as a very accurate and dependable presence tracker. all you need to do is find out the MAC addresses and add them. this is part of my config:

```
manager:
  topic_subscription:
    update_all:
      topic: homeassistant/status
      payload: online
  workers:
    blescanmulti:
      args:
        devices:
          katiaschluessel: CD:XX:XX:XX:XX:XX
          autoschluessel: E0:XX:XX:XX:XX:XX
          felixschluessel: C3:XX:XX:XX:XX:XX 
        topic_prefix: blescan
        available_payload: home
        unavailable_payload: not_home
        available_timeout: 0
        unavailable_timeout: 120
        scan_timeout: 10
        scan_passive: true
      update_interval: 60

```
