### ISSUE TITLE
I need help to configure the gateway to support multiple Soil sensor 

### ISSUE THREAD

**Issue by vdj69** [zewelor/bt-mqtt-gateway#192]
Hi,
In my garden, there are 25 flower plants in 25 different flower pots which are very special to me I want to monitor them with 'Xiaomi Mi Flora Monitor sensor'. And for this I have the following queries:
1. Do I need 25 different workers to or we can do with a single worker as these sensors are same type?
2. How many number of sensors are supported by this gateway? 
3. Does this gateway support BLE MESH or ZIGBEE?
4. How to add other protocols like RS232 or I2C to this gateway?

**Comment by koenvervloesem** [comment]
I can answer question 1: you just have to add every sensor to the `miflora` worker, like this in `config.yaml`:

```
  workers:
    miflora:
      args:
        devices:
          aglaonema: 01:23:45:67:89:AB
          dracaena: CD:EF:01:23:45:67
          ...
        topic_prefix: miflora
      update_interval: 300
```

I have three of these Xiaomi Mi Flora sensors running with such a configuration. I don't think there's a limit on the number of sensors supported.
