### ISSUE TITLE
Rpi lywsd03 config error

### ISSUE THREAD

**Issue by olup** [zewelor/bt-mqtt-gateway#210]
[] I've read the [Troubleshooting Wiki](https://github.com/zewelor/bt-mqtt-gateway/wiki/Troubleshooting), my problem is not described there and I am  already using the specified minimum bluez version.

**Describe the bug**
I get `TypeError: __init__() got multiple values for argument 'command_timeout'` on startup.

Config :
```
mqtt:
  host: localhost                                                                    port: 1883
  topic_prefix: ble  
  ca_verify: False                                                                   
  client_id: bt-mqtt-gateway
  availability_topic: lwt_topic
manager:                                                                             
  workers:
   lywsd03mmc:
      args:
        devices:
          bedroom: A4:C1:38:1A:B8:52
        topic_prefix: mijasensor
        passive: False
        command_timeout: 30
      update_interval: 120
```
Fresh clone or fresh docker image - same story.
Omitting command_timeout on the worker object throws as this argument seems required.

I am in stock firmware for the sensor.
