### ISSUE TITLE
Home Assistant auto discovery

### ISSUE THREAD

**Issue by twsl** [zewelor/bt-mqtt-gateway#211]
**Is your feature request related to a problem? Please describe.**
Since Home Assistant is moving towards UI configuration and away from yaml files, having devices as entities in the UI would be nice.

**Describe the solution you'd like**
I'd love to get the mqtt entities automatically discovered by home assistant.

**Describe alternatives you've considered**
configuring them manually.

**Additional context**
-

**Comment by zewelor** [comment]
Hmm they should be auto discovered by mqtt ? Do you have mqtt autodiscovery on, and enabled in gateway ?

**Comment by twsl** [comment]
They are visible in mqtt, but not as device in home assistant

**Comment by lepinkainen** [comment]
Auto discovery works for me, devices are detected in Home Assistant, but the values are never received for some reason.

**Comment by twsl** [comment]
@lepinkainen can you share your config?

**Comment by lepinkainen** [comment]
config.yaml:
```
mqtt:
  host: 192.168.1.12
  port: 1883
  #username: user
  #password: password
  #ca_cert: /etc/ssl/certs/ca-certificates.crt # Uncomment to enable MQTT TLS, update path to appropriate location.
  #ca_verify: False              # Verify TLS certificate chain and host, disable for testing with self-signed certificates, default to True
  #topic_prefix: hostname         # All messages will have that prefix added, remove if you dont need this.
  client_id: bt-mqtt-gateway
  availability_topic: lwt_topic

manager:
  sensor_config:
    topic: homeassistant
    retain: true
  topic_subscription:
    update_all:
      topic: homeassistant/status
      payload: online
  command_timeout: 35

  workers:
    ruuvitag:
      args:
        devices:
          livingroom: c3:b3:40:aa:71:23
          bedroom: d9:0b:7c:9c:56:2b
          balcony: fa:13:e6:13:62:aa
        topic_prefix: ruuvitag_ha
      update_interval: 30
```

docker-compose.yml:
```
version: '3.7'

services:
  bt-mqtt-gateway:
    image: zewelor/bt-mqtt-gateway
    container_name: bt-mqtt-gateway
    restart: always
    # Uncomment to enable debug
    environment:
      - DEBUG=true
    volumes:
      - ./config.yaml:/config.yaml
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
```

Alternating between `privileged: true` and the cap_add options seems to do nothing of value.

With this setup, everything appears on HA as they should, but the statuses never update. No messages are received in `ruuvitag_ha/#`. Running with `debug=true` doesn't log any errors at all.

The tags _do_ work, I've got a similar system built by myself, but can't be arsed to code the HA autodiscovery part, so I'm trying this one. (Also this would allow me to combine the Xiaomi BLE meters in the same setup)
