### ISSUE TITLE
topic_subscription not working as expected

### ISSUE THREAD

**Issue by andrey-yantsen** [zewelor/bt-mqtt-gateway#235]
I have 3 instances on 3 different rpi0w, in different rooms. All of them are used to control my AM43 blinds and to prevent conflicts when processing an MQTT command, they have `topic_prefix` set depending on the rpi0w's hostname.

In the config I have the following bit:
```
manager:
  topic_subscription:
    update_all:
      topic: homeassistant/status
      payload: online
```

The idea is to have up-to-date data sent to MQTT every time HASS restarts. Unfortunately, the defined `topic` gets concatenated with `topic_prefix`. It would be good to have an extra option in the `topic_subscription` in order to prevent such concatenation.
