### ISSUE TITLE
wrong time on eq3 thermostat (wrong time zone?)

### ISSUE THREAD

**Issue by renarena** [zewelor/bt-mqtt-gateway#239]
I've read the [Troubleshooting Wiki](https://github.com/zewelor/bt-mqtt-gateway/wiki/Troubleshooting), my problem is not described there and I am  already using the specified minimum bluez version.

**Describe the bug**
as soon as i start bt-mqtt-gateway my thermostats time is off 1 hour.
if i stop it, the time stays correct after changing it.

**Expected behavior**
thermostats use correct time

**Config**
```
/home/pi/.config/bt-mqtt-gateway/config.yaml   [B---]  0 L:[  1+ 0   1/ 41] *(0   /2197b) 0109 0x06D                                        [*][X]
  workers:
    thermostat:
      args:
        devices:
          kitchen: 
            mac: xxxxxxxxxxxxxxxxx
            discovery_temperature_topic: kitchen/temperature       
            discovery_temperature_template: "{{ value_json.temperature }}"  
        topic_prefix: thermostat
      topic_subscription: thermostat/+/+/set
      update_interval: 60
```

**Debug gateway logs**
run gateway.py with -d switch and paste formatted output log

**Server (please complete the following information):**
 - OS: [Linux]
 - Distro: [ Raspbian]
 - Version [latest docker]

**Additional context**
this may cause the problem - it does not consider the timezone set in raspbian:
https://github.com/rytilahti/python-eq3bt/issues/25
