### ISSUE TITLE
Missing MQTT messages

### ISSUE THREAD

**Issue by adamcodemaker** [zewelor/bt-mqtt-gateway#262]
I have a config with one thermostat. Sometimes the manager does not receive mqtt messages.
When I send message to mqtt broker to set temperature to some value there is no debug message at all.

![image](https://user-images.githubusercontent.com/25587877/190877625-3095fb0c-bd6d-48b3-b604-90f3222881b4.png)

Just like it was ignored or something.
There should be loge like this.
`2022-09-17 21:42:17,028 DEBUG bt-mqtt-gw.workers_manager workers_manager.py:193:_on_command_wrapper - Received command for thermostat on thermostat/office-biuro/target_temperature/set: b'17'`
Sometimes message is received but sometimes not. I don't know why. Manager should receive every message from mqtt broker. I use my mqtt broker ([Eclipse Mosquitto](https://mosquitto.org/)) for years without any problems so the broker is ok.
Even with messages with retain flag are missing.

**To Reproduce**
1. Try to send message to change target temperature
2. Do it couple of times
3. Observe that some messages are missing in logs 

**Expected behavior**
Every message from mqtt broker should be received by manager and handled properly.

**Config**
```
mqtt:
  host: 192.168.0.90
  port: 1883
  username: xxx
  password: yyy
  client_id: bt-mqtt-gateway
  availability_topic: lwt_topic

manager:
  sensor_config:
    topic: homeassistant
    retain: true
  topic_subscription:
    update_all:
      topic: homeassistant/status
      payload: online
  command_timeout: 25
  update_retries: 3
  workers:
    thermostat:
      args:
        devices:
          office-biuro:
            mac: XX:XX:XX:XX:XX:XX
            discovery_temperature_topic: bt-scanner/sensor/x1_temperature/state
        topic_prefix: thermostat
      topic_subscription: thermostat/+/+/set
      update_interval: 60
```

**Server (please complete the following information):**
 - OS: linux
 - Distro: raspbian
 - Version: 11 bullseye
 - Hardware: raspberry pi zero w
 - runs on docker
