### ISSUE TITLE
Subscribing to command topics seems broken

### ISSUE THREAD

**Issue by cybe** [zewelor/bt-mqtt-gateway#34]
Hello,

I'm having difficulties sending commands to a thermostat, perhaps similar to #33. The topic subscription succeeds, but the callback is never executed.

I enabled debug logging for mqtt via `self.mqttc.enable_logger(logger=_LOGGER)` in `mqtt.py`. These are my observations:

1. The mqtt client reconnects to the mqtt server right after each update interval, thereby replacing the previous connection:
```
# ./gateway.py -d
Starting
Added: thermostat with 20 seconds interval
Subscribing to: thermostat/+/+/set
Sending CONNECT (u1, p1, wr0, wq0, wf0, c0, k60) client_id=b'bt-mqtt-gateway-ham'
Sending SUBSCRIBE (d0, m1) [(b'bmg-ham/thermostat/+/+/set', 0)]
Received CONNACK (1, 0)
Received SUBACK
Updating all workers
[{'topic': 'thermostat/wohnen/low_battery', 'payload': False}, {'topic': 'thermostat/wohnen/valve_state', 'payload': 13}, {'topic': 'thermostat/wohnen/target_temperature', 'payload': 21.0}, {'topic': 'thermostat/wohnen/window_open', 'payload': False}, {'topic': 'thermostat/wohnen/locked', 'payload': False}, {'topic': 'thermostat/wohnen/mode', 'payload': 'manual'}, {'topic': 'thermostat/wohnen/away', 'payload': 'off'}]
Sending CONNECT (u1, p1, wr0, wq0, wf0, c0, k60) client_id=b'bt-mqtt-gateway-ham'
Received CONNACK (0, 0)
```
This corresponds with the logfiles from mosquitto. On these reconnects, the subscriptions are not renewed. This behavior seems to be incorrect, as there should't be made any new connections. Mosquitto log:
```
1544870901: New connection from 172.19.0.1 on port 1883.
1544870901: Socket error on client bt-mqtt-gateway, disconnecting.
1544870901: New client connected from 172.19.0.1 as bt-mqtt-gateway (c0, k60, u'bt-mqtt-gateway').
1544870904: New connection from 172.19.0.1 on port 1883.
1544870904: Client bt-mqtt-gateway already connected, closing old connection.
1544870904: Socket error on client bt-mqtt-gateway, disconnecting.
1544870904: New client connected from 172.19.0.1 as bt-mqtt-gateway (c1, k60, u'bt-mqtt-gateway').
1544870904: Client bt-mqtt-gateway disconnected.
1544870905: New connection from 172.19.0.1 on port 1883.
1544870905: New client connected from 172.19.0.1 as bt-mqtt-gateway (c0, k60, u'bt-mqtt-gateway').
```

2. If I replace `self.mqttc.loop_start()` in `mqtt.py` with `self.mqttc.loop_forever()` the callbacks are processed:
```
# ./gateway.py -d
Starting
Added: thermostat with 20 seconds interval
Subscribing to: thermostat/+/+/set
Sending CONNECT (u1, p1, wr0, wq0, wf0, c0, k60) client_id=b'bt-mqtt-gateway-ham'
Sending SUBSCRIBE (d0, m1) [(b'bmg-ham/thermostat/+/+/set', 0)]
Received CONNACK (1, 0)
Received SUBACK
Received PUBLISH (d0, q0, r0, m0), 'bmg-ham/thermostat/wohnen/target_temperature/set', ...  (4 bytes)
on command wrapper for with bmg-ham/thermostat/wohnen/target_temperature/set: b'20.0'
```
However, as `self.mqttc.loop_forever()` is a blocking call, the scheduled worker updates aren't running.

For reference, this is my config:
```
mqtt:
  host: ***
  port: 1883
  username: bt-mqtt-gateway
  password: ***
  topic_prefix: bmg-ham
  client_id: bt-mqtt-gateway-ham

manager:
  workers:
    thermostat:
      args:
        devices:
          wohnen: 00:11:22:33:44:55
        topic_prefix: thermostat
      topic_subscription: thermostat/+/+/set
      update_interval: 20
```
